version: '3.8'

services:
  # Base de données PostgreSQL
  db:
    image: postgres:15
    container_name: edu_db_prod
    environment:
      POSTGRES_USER: eduuser
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: edutasks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Application Django avec Gunicorn
  web:
    image: ${DOCKER_USERNAME}/edu-task-manager:latest
    container_name: edu_app_prod
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 4
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=edutasks
      - DB_USER=eduuser
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - ALLOWED_HOSTS=${DEPLOY_HOST},localhost
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - static_files:/app/static
      - media_files:/app/media

  # Serveur Nginx
  nginx:
    image: nginx:alpine
    container_name: edu_nginx_prod
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_files:/static:ro
      - media_files:/media:ro
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  static_files:
  media_files: