# Generated by Django 5.0.6 on 2026-07-14 17:12

import assignments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_remove_submission_attachments_discipline_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=assignments.models.submission_file_path),
        ),
    ]
