name: CD Pipeline

on:
  push:
    branches: [ "main", "test-ci" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Construire l'image Docker
        run: docker build -t edu-task-manager:latest .

      - name: Vérifier la construction
        run: |
          echo "✅ Image construite avec succès!"
          docker images
